export const IPC_ACTIONS = {
    Window: {
        SET_LICENSE_KEY: 'SET_LICENSE_KEY',
        GET_LICENSE_KEY: 'GET_LICENSE_KEY',
        SET_MARKUP_PERCENTAGE: 'SET_MARKUP_PERCENTAGE',
        GET_MARKUP_PERCENTAGE: 'GET_MARKUP_PERCENTAGE',
        SET_VAT_PAYER_STATUS: 'SET_VAT_PAYER_STATUS',
        GET_VAT_PAYER_STATUS: 'GET_VAT_PAYER_STATUS',
        SELECT_SAVE_PATH: 'SELECT_SAVE_PATH',
        OPEN_FILE_DIALOG: 'OPEN_FILE_DIALOG',
        SET_FACTURIS_TYPE: "SET_FACTURIS_TYPE",
        GET_FACTURIS_TYPE: "GET_FACTURIS_TYPE",
        PROCESS_XML_FOR_FREYA: 'PROCESS_XML_FOR_FREYA',
        PROCESS_XML_FOR_OBLIO: 'PROCESS_XML_FOR_OBLIO',
        PROCESS_XML_FOR_SMARTBILL: 'PROCESS_XML_FOR_SMARTBILL',
        GET_DEVICE_ID: "GET_DEVICE_ID",
    }
};

